# Generated by Django 5.2.5 on 2025-08-24 19:52

import django.core.validators
import django.db.models.deletion
import menu.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("sort", models.PositiveIntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=menu.models.dish_image_path
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=100)),
                ("status", models.BooleanField(default=True, help_text="是否上架")),
                ("sold", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dishes",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["status"], name="menu_dish_status_07c337_idx"),
                    models.Index(
                        fields=["category", "status"],
                        name="menu_dish_categor_9be982_idx",
                    ),
                    models.Index(fields=["-sold"], name="menu_dish_sold_185857_idx"),
                    models.Index(fields=["price"], name="menu_dish_price_497910_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="dish_price_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock__gte", 0)),
                        name="dish_stock_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sold__gte", 0)),
                        name="dish_sold_non_negative",
                    ),
                ],
            },
        ),
    ]
