# Generated by Django 5.2.5 on 2025-08-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dish",
            unique_together={("restaurant", "name")},
        ),
    ]
