# Generated by Django 5.2.5 on 2025-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="service_type",
            field=models.CharField(
                choices=[("DELIVERY", "外送"), ("DINE_IN", "堂食")],
                default="DELIVERY",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table_no",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
